CREATE DATABASE IF NOT EXISTS db_business_model_DEVELOP
;
CREATE DATABASE IF NOT EXISTS db_data_model_DEVELOP
;
CREATE DATABASE IF NOT EXISTS db_stage_DEVELOP
;
CREATE DATABASE IF NOT EXISTS db_business_model
;
CREATE DATABASE IF NOT EXISTS db_data_model
;
CREATE DATABASE IF NOT EXISTS db_stage
;