import type { PipelineTask } from "./types";
import { deepAnonymize } from "./demo-mode";
import { isTransparentSystemDdlTask } from "./task-type-utils";

const RAW_INITIAL_PIPELINE_TASKS: PipelineTask[] = [
  // ── dag_ecom_app_orders_daily (snapshot) ──
  {
    id: "ecom-orders-1",
    name: "create_table_stage",
    dagName: "dag_ecom_app_orders_daily",
    stage: "ddl",
    taskType: "snapshot",
    sqlFilePath: "dags/ecom_app/orders_daily/ddl/create_table_stage.sql",
    order: 1,
  },
  {
    id: "ecom-orders-2",
    name: "create_table_data_model",
    dagName: "dag_ecom_app_orders_daily",
    stage: "ddl",
    taskType: "snapshot",
    sqlFilePath: "dags/ecom_app/orders_daily/ddl/create_table_data_model.sql",
    order: 2,
  },
  {
    id: "ecom-orders-3",
    name: "ddl_bi_custom",
    dagName: "dag_ecom_app_orders_daily",
    stage: "ddl",
    taskType: "snapshot",
    sqlFilePath: "dags/ecom_app/orders_daily/ddl/bi_custom_ddl.sql",
    order: 3,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "warehouse_postgres" },
      query: { file: "bi_custom_ddl.sql", timezone: "UTC" },
    },
  },
  {
    id: "ecom-orders-4",
    name: "extract_orders_raw",
    dagName: "dag_ecom_app_orders_daily",
    stage: "extract",
    taskType: "snapshot",
    sqlFilePath: "dags/ecom_app/orders_daily/extract/extract_orders.sql",
    order: 4,
    taskConfig: {
      expectedWorkload: "medium",
      targetTableName: "orders",
      connection: { source: "sqlserver_ecom_src", target: "warehouse_postgres" },
      query: { file: "extract_orders.sql", timezone: "US/Eastern" },
    },
  },
  {
    id: "ecom-orders-5",
    name: "transform_orders",
    dagName: "dag_ecom_app_orders_daily",
    stage: "transform",
    taskType: "snapshot",
    sqlFilePath: "dags/ecom_app/orders_daily/transform/transform_orders.sql",
    order: 5,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "warehouse_postgres" },
      query: { file: "transform_orders.sql", timezone: "US/Eastern" },
    },
  },
  {
    id: "ecom-orders-6",
    name: "cleanup_orders_stage",
    dagName: "dag_ecom_app_orders_daily",
    stage: "transform",
    taskType: "snapshot",
    sqlFilePath: "dags/ecom_app/orders_daily/transform/cleanup_stage.sql",
    order: 6,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "warehouse_postgres" },
      query: { file: "cleanup_stage.sql", timezone: "US/Eastern" },
    },
  },
  {
    id: "ecom-orders-7",
    name: "load_orders",
    dagName: "dag_ecom_app_orders_daily",
    stage: "load",
    taskType: "snapshot",
    sqlFilePath: "dags/ecom_app/orders_daily/load/load_orders.sql",
    order: 7,
    taskConfig: {
      expectedWorkload: "medium",
      connection: { source: "warehouse_postgres", target: "warehouse_postgres" },
      query: { file: "load_orders.sql", timezone: "US/Eastern" },
      loadTarget: { type: "DB", connection: { target: "warehouse_postgres" } },
    },
  },
  {
    id: "ecom-orders-8",
    name: "dqa_order_dates_sanity",
    dagName: "dag_ecom_app_orders_daily",
    stage: "dqa",
    taskType: "snapshot",
    sqlFilePath: "dags/ecom_app/orders_daily/dqa/orders_dates_sanity.sql",
    order: 8,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "warehouse_postgres" },
      query: { file: "orders_dates_sanity.sql", timezone: "US/Eastern" },
      dqa: { queryType: "single_query_notification", alertKind: "warning", tolerance: 0 },
    },
  },
  {
    id: "ecom-orders-9",
    name: "dqa_orders_source_vs_target_counts",
    dagName: "dag_ecom_app_orders_daily",
    stage: "dqa",
    taskType: "snapshot",
    // Primary file for this task is the source query (task opens split editor).
    sqlFilePath: "dags/ecom_app/orders_daily/dqa/source_orders_count_by_day.sql",
    order: 9,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "sqlserver_ecom_src", target: "warehouse_postgres" },
      query: { file: "source_orders_count_by_day.sql", timezone: "US/Eastern" },
      dqa: {
        queryType: "source_vs_target_query_comparison",
        alertKind: "error",
        tolerance: 0.01,
        sourceQueryFile: "source_orders_count_by_day.sql",
        targetQueryFile: "target_orders_count_by_day.sql",
        comparisonMetric: "count_per_day",
        groupBy: ["day"],
      },
    },
  },

  // ── dag_ecom_app_customers_snapshot (snapshot) ──
  {
    id: "ecom-customers-1",
    name: "create_table_stage",
    dagName: "dag_ecom_app_customers_snapshot",
    stage: "ddl",
    taskType: "snapshot",
    sqlFilePath: "dags/ecom_app/customers_snapshot/ddl/create_table_stage.sql",
    order: 1,
  },
  {
    id: "ecom-customers-2",
    name: "create_table_data_model",
    dagName: "dag_ecom_app_customers_snapshot",
    stage: "ddl",
    taskType: "snapshot",
    sqlFilePath: "dags/ecom_app/customers_snapshot/ddl/create_table_data_model.sql",
    order: 2,
  },
  {
    id: "ecom-customers-3",
    name: "ddl_bi_custom",
    dagName: "dag_ecom_app_customers_snapshot",
    stage: "ddl",
    taskType: "snapshot",
    sqlFilePath: "dags/ecom_app/customers_snapshot/ddl/bi_custom_ddl.sql",
    order: 3,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "warehouse_postgres" },
      query: { file: "bi_custom_ddl.sql", timezone: "UTC" },
    },
  },
  {
    id: "ecom-customers-4",
    name: "extract_customers_raw",
    dagName: "dag_ecom_app_customers_snapshot",
    stage: "extract",
    taskType: "snapshot",
    sqlFilePath: "dags/ecom_app/customers_snapshot/extract/extract_customers.sql",
    order: 4,
    taskConfig: {
      expectedWorkload: "medium",
      targetTableName: "customers",
      connection: { source: "sqlserver_ecom_src", target: "warehouse_postgres" },
      query: { file: "extract_customers.sql", timezone: "US/Eastern" },
    },
  },
  {
    id: "ecom-customers-5",
    name: "transform_customers",
    dagName: "dag_ecom_app_customers_snapshot",
    stage: "transform",
    taskType: "snapshot",
    sqlFilePath: "dags/ecom_app/customers_snapshot/transform/transform_customers.sql",
    order: 5,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "warehouse_postgres" },
      query: { file: "transform_customers.sql", timezone: "US/Eastern" },
    },
  },
  {
    id: "ecom-customers-6",
    name: "cleanup_customers_stage",
    dagName: "dag_ecom_app_customers_snapshot",
    stage: "transform",
    taskType: "snapshot",
    sqlFilePath: "dags/ecom_app/customers_snapshot/transform/cleanup_stage.sql",
    order: 6,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "warehouse_postgres" },
      query: { file: "cleanup_stage.sql", timezone: "US/Eastern" },
    },
  },
  {
    id: "ecom-customers-7",
    name: "load_customers",
    dagName: "dag_ecom_app_customers_snapshot",
    stage: "load",
    taskType: "snapshot",
    sqlFilePath: "dags/ecom_app/customers_snapshot/load/load_customers.sql",
    order: 7,
    taskConfig: {
      expectedWorkload: "medium",
      connection: { source: "warehouse_postgres", target: "warehouse_postgres" },
      query: { file: "load_customers.sql", timezone: "US/Eastern" },
      loadTarget: { type: "DB", connection: { target: "warehouse_postgres" } },
    },
  },
  {
    id: "ecom-customers-8",
    name: "dqa_customer_dates_sanity",
    dagName: "dag_ecom_app_customers_snapshot",
    stage: "dqa",
    taskType: "snapshot",
    sqlFilePath: "dags/ecom_app/customers_snapshot/dqa/customers_dates_sanity.sql",
    order: 8,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "warehouse_postgres" },
      query: { file: "customers_dates_sanity.sql", timezone: "US/Eastern" },
      dqa: { queryType: "single_query_notification", alertKind: "warning", tolerance: 0 },
    },
  },

  // ── dag_ecom_app_inventory_hourly (incremental) ──
  {
    id: "ecom-inventory-1",
    name: "create_table_stage",
    dagName: "dag_ecom_app_inventory_hourly",
    stage: "ddl",
    taskType: "incremental",
    sqlFilePath: "dags/ecom_app/inventory_hourly/ddl/create_table_stage.sql",
    order: 1,
  },
  {
    id: "ecom-inventory-2",
    name: "create_table_data_model",
    dagName: "dag_ecom_app_inventory_hourly",
    stage: "ddl",
    taskType: "incremental",
    sqlFilePath: "dags/ecom_app/inventory_hourly/ddl/create_table_data_model.sql",
    order: 2,
  },
  {
    id: "ecom-inventory-3",
    name: "ddl_bi_custom",
    dagName: "dag_ecom_app_inventory_hourly",
    stage: "ddl",
    taskType: "incremental",
    sqlFilePath: "dags/ecom_app/inventory_hourly/ddl/bi_custom_ddl.sql",
    order: 3,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "warehouse_postgres" },
      query: { file: "bi_custom_ddl.sql", timezone: "UTC" },
    },
  },
  {
    id: "ecom-inventory-4",
    name: "extract_inventory_raw",
    dagName: "dag_ecom_app_inventory_hourly",
    stage: "extract",
    taskType: "incremental",
    sqlFilePath: "dags/ecom_app/inventory_hourly/extract/extract_inventory_levels.sql",
    order: 4,
    taskConfig: {
      expectedWorkload: "high",
      targetTableName: "inventory_levels",
      connection: { source: "postgres_ecom_src", target: "warehouse_postgres" },
      query: { file: "extract_inventory_levels.sql", timezone: "US/Eastern" },
      loadTarget: { type: "DB", connection: { target: "warehouse_postgres" } },
    },
  },
  {
    id: "ecom-inventory-5",
    name: "transform_inventory_levels",
    dagName: "dag_ecom_app_inventory_hourly",
    stage: "transform",
    taskType: "incremental",
    sqlFilePath: "dags/ecom_app/inventory_hourly/transform/transform_inventory_levels.sql",
    order: 5,
    taskConfig: {
      expectedWorkload: "medium",
      connection: { source: "warehouse_postgres" },
      query: { file: "transform_inventory_levels.sql", timezone: "US/Eastern" },
    },
  },
  {
    id: "ecom-inventory-6",
    name: "cleanup_inventory_stage",
    dagName: "dag_ecom_app_inventory_hourly",
    stage: "transform",
    taskType: "incremental",
    sqlFilePath: "dags/ecom_app/inventory_hourly/transform/cleanup_stage.sql",
    order: 6,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "warehouse_postgres" },
      query: { file: "cleanup_stage.sql", timezone: "US/Eastern" },
    },
  },
  {
    id: "ecom-inventory-7",
    name: "load_inventory_levels",
    dagName: "dag_ecom_app_inventory_hourly",
    stage: "load",
    taskType: "incremental",
    sqlFilePath: "dags/ecom_app/inventory_hourly/load/load_inventory_levels.sql",
    order: 7,
    taskConfig: {
      expectedWorkload: "medium",
      connection: { source: "warehouse_postgres", target: "warehouse_postgres" },
      query: { file: "load_inventory_levels.sql", timezone: "US/Eastern" },
      loadTarget: { type: "DB", connection: { target: "warehouse_postgres" } },
    },
  },
  {
    id: "ecom-inventory-8",
    name: "dqa_inventory_source_vs_target_counts",
    dagName: "dag_ecom_app_inventory_hourly",
    stage: "dqa",
    taskType: "incremental",
    sqlFilePath: "dags/ecom_app/inventory_hourly/dqa/source_inventory_levels_count_by_day.sql",
    order: 8,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "postgres_ecom_src", target: "warehouse_postgres" },
      query: { file: "source_inventory_levels_count_by_day.sql", timezone: "US/Eastern" },
      dqa: {
        queryType: "source_vs_target_query_comparison",
        alertKind: "error",
        tolerance: 0.01,
        sourceQueryFile: "source_inventory_levels_count_by_day.sql",
        targetQueryFile: "target_inventory_levels_count_by_day.sql",
        comparisonMetric: "count_per_day",
        groupBy: ["day"],
      },
    },
  },

  // ── dag_store_pos_store_sales_daily (snapshot) ──
  {
    id: "pos-sales-1",
    name: "create_table_stage",
    dagName: "dag_store_pos_store_sales_daily",
    stage: "ddl",
    taskType: "snapshot",
    sqlFilePath: "dags/store_pos/store_sales_daily/ddl/create_table_stage.sql",
    order: 1,
  },
  {
    id: "pos-sales-2",
    name: "create_table_data_model",
    dagName: "dag_store_pos_store_sales_daily",
    stage: "ddl",
    taskType: "snapshot",
    sqlFilePath: "dags/store_pos/store_sales_daily/ddl/create_table_data_model.sql",
    order: 2,
  },
  {
    id: "pos-sales-3",
    name: "ddl_bi_custom",
    dagName: "dag_store_pos_store_sales_daily",
    stage: "ddl",
    taskType: "snapshot",
    sqlFilePath: "dags/store_pos/store_sales_daily/ddl/bi_custom_ddl.sql",
    order: 3,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "warehouse_postgres" },
      query: { file: "bi_custom_ddl.sql", timezone: "UTC" },
    },
  },
  {
    id: "pos-sales-4",
    name: "extract_store_sales_raw",
    dagName: "dag_store_pos_store_sales_daily",
    stage: "extract",
    taskType: "snapshot",
    sqlFilePath: "dags/store_pos/store_sales_daily/extract/extract_store_sales.sql",
    order: 4,
    taskConfig: {
      expectedWorkload: "medium",
      targetTableName: "store_sales",
      connection: { source: "sqlserver_pos_src", target: "warehouse_postgres" },
      query: { file: "extract_store_sales.sql", timezone: "UTC" },
    },
  },
  {
    id: "pos-sales-5",
    name: "transform_store_sales",
    dagName: "dag_store_pos_store_sales_daily",
    stage: "transform",
    taskType: "snapshot",
    sqlFilePath: "dags/store_pos/store_sales_daily/transform/transform_store_sales.sql",
    order: 5,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "warehouse_postgres" },
      query: { file: "transform_store_sales.sql", timezone: "UTC" },
    },
  },
  {
    id: "pos-sales-6",
    name: "cleanup_store_sales_stage",
    dagName: "dag_store_pos_store_sales_daily",
    stage: "transform",
    taskType: "snapshot",
    sqlFilePath: "dags/store_pos/store_sales_daily/transform/cleanup_stage.sql",
    order: 6,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "warehouse_postgres" },
      query: { file: "cleanup_stage.sql", timezone: "UTC" },
    },
  },
  {
    id: "pos-sales-7",
    name: "load_store_sales",
    dagName: "dag_store_pos_store_sales_daily",
    stage: "load",
    taskType: "snapshot",
    sqlFilePath: "dags/store_pos/store_sales_daily/load/load_store_sales.sql",
    order: 7,
    taskConfig: {
      expectedWorkload: "medium",
      connection: { source: "warehouse_postgres", target: "warehouse_postgres" },
      query: { file: "load_store_sales.sql", timezone: "UTC" },
      loadTarget: { type: "DB", connection: { target: "warehouse_postgres" } },
    },
  },
  {
    id: "pos-sales-8",
    name: "dqa_sales_dates_sanity",
    dagName: "dag_store_pos_store_sales_daily",
    stage: "dqa",
    taskType: "snapshot",
    sqlFilePath: "dags/store_pos/store_sales_daily/dqa/store_sales_dates_sanity.sql",
    order: 8,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "warehouse_postgres" },
      query: { file: "store_sales_dates_sanity.sql", timezone: "UTC" },
      dqa: { queryType: "single_query_notification", alertKind: "warning", tolerance: 0 },
    },
  },

  // ── dag_ad_platform_campaign_metrics_hourly (incremental) ──
  {
    id: "ads-campaign-1",
    name: "create_table_stage",
    dagName: "dag_ad_platform_campaign_metrics_hourly",
    stage: "ddl",
    taskType: "incremental",
    sqlFilePath: "dags/ad_platform/campaign_metrics_hourly/ddl/create_table_stage.sql",
    order: 1,
  },
  {
    id: "ads-campaign-2",
    name: "create_table_data_model",
    dagName: "dag_ad_platform_campaign_metrics_hourly",
    stage: "ddl",
    taskType: "incremental",
    sqlFilePath: "dags/ad_platform/campaign_metrics_hourly/ddl/create_table_data_model.sql",
    order: 2,
  },
  {
    id: "ads-campaign-3",
    name: "ddl_bi_custom",
    dagName: "dag_ad_platform_campaign_metrics_hourly",
    stage: "ddl",
    taskType: "incremental",
    sqlFilePath: "dags/ad_platform/campaign_metrics_hourly/ddl/bi_custom_ddl.sql",
    order: 3,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "warehouse_postgres" },
      query: { file: "bi_custom_ddl.sql", timezone: "UTC" },
    },
  },
  {
    id: "ads-campaign-4",
    name: "extract_campaign_metrics_raw",
    dagName: "dag_ad_platform_campaign_metrics_hourly",
    stage: "extract",
    taskType: "incremental",
    sqlFilePath: "dags/ad_platform/campaign_metrics_hourly/extract/extract_campaign_metrics.sql",
    order: 4,
    taskConfig: {
      expectedWorkload: "high",
      targetTableName: "campaign_metrics",
      connection: { source: "postgres_ads_src", target: "warehouse_postgres" },
      query: { file: "extract_campaign_metrics.sql", timezone: "Europe/Madrid" },
    },
  },
  {
    id: "ads-campaign-5",
    name: "transform_campaign_metrics",
    dagName: "dag_ad_platform_campaign_metrics_hourly",
    stage: "transform",
    taskType: "incremental",
    sqlFilePath: "dags/ad_platform/campaign_metrics_hourly/transform/transform_campaign_metrics.sql",
    order: 5,
    taskConfig: {
      expectedWorkload: "medium",
      connection: { source: "warehouse_postgres" },
      query: { file: "transform_campaign_metrics.sql", timezone: "Europe/Madrid" },
    },
  },
  {
    id: "ads-campaign-6",
    name: "cleanup_campaign_metrics_stage",
    dagName: "dag_ad_platform_campaign_metrics_hourly",
    stage: "transform",
    taskType: "incremental",
    sqlFilePath: "dags/ad_platform/campaign_metrics_hourly/transform/cleanup_stage.sql",
    order: 6,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "warehouse_postgres" },
      query: { file: "cleanup_stage.sql", timezone: "Europe/Madrid" },
    },
  },
  {
    id: "ads-campaign-7",
    name: "load_campaign_metrics",
    dagName: "dag_ad_platform_campaign_metrics_hourly",
    stage: "load",
    taskType: "incremental",
    sqlFilePath: "dags/ad_platform/campaign_metrics_hourly/load/load_campaign_metrics.sql",
    order: 7,
    taskConfig: {
      expectedWorkload: "medium",
      connection: { source: "warehouse_postgres", target: "warehouse_postgres" },
      query: { file: "load_campaign_metrics.sql", timezone: "Europe/Madrid" },
      loadTarget: { type: "DB", connection: { target: "warehouse_postgres" } },
    },
  },
  {
    id: "ads-campaign-8",
    name: "dqa_campaign_dates_sanity",
    dagName: "dag_ad_platform_campaign_metrics_hourly",
    stage: "dqa",
    taskType: "incremental",
    sqlFilePath: "dags/ad_platform/campaign_metrics_hourly/dqa/campaign_metrics_dates_sanity.sql",
    order: 8,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "warehouse_postgres" },
      query: { file: "campaign_metrics_dates_sanity.sql", timezone: "Europe/Madrid" },
      dqa: { queryType: "single_query_notification", alertKind: "warning", tolerance: 0 },
    },
  },
];

export const initialPipelineTasks: PipelineTask[] = deepAnonymize(RAW_INITIAL_PIPELINE_TASKS);

export function getTasksForPipeline(tasks: PipelineTask[], dagName: string): PipelineTask[] {
  return tasks
    .filter((t) => t.dagName === dagName)
    .sort((a, b) => a.order - b.order);
}

export function getNonDdlTasksForPipeline(tasks: PipelineTask[], dagName: string): PipelineTask[] {
  return tasks
    .filter((t) => t.dagName === dagName && !isTransparentSystemDdlTask(t.name, t.sqlFilePath))
    .sort((a, b) => a.order - b.order);
}
