import { PipelineTask } from "./types";
import { isTransparentSystemDdlTask } from "./task-type-utils";
import { deepAnonymize } from "./demo-mode";

// 5 tasks per DAG × 5 DAGs = 25 tasks
// Pattern per DAG: create_table_stage → create_table_data_model → extract_and_load → data_model_task → delete_logs

const RAW_INITIAL_PIPELINE_TASKS: PipelineTask[] = [
  // ── dag_CRM_integration_dbo_AccountReference (snapshot) ──
  {
    id: "crm-acctref-1",
    name: "ddl_stage_AccountReference",
    dagName: "dag_CRM_integration_dbo_AccountReference",
    stage: "ddl",
    taskType: "snapshot",
    sqlFilePath: "dags/CRM_integration/AccountReference/ddl/create_table_stage.sql",
    order: 1,
  },
  {
    id: "crm-acctref-2",
    name: "ddl_datamodel_AccountReference",
    dagName: "dag_CRM_integration_dbo_AccountReference",
    stage: "ddl",
    taskType: "snapshot",
    sqlFilePath: "dags/CRM_integration/AccountReference/ddl/create_table_data_model.sql",
    order: 2,
  },
  {
    id: "crm-acctref-2b",
    name: "ddl_bi_custom_AccountReference",
    dagName: "dag_CRM_integration_dbo_AccountReference",
    stage: "ddl",
    taskType: "snapshot",
    sqlFilePath: "dags/CRM_integration/AccountReference/ddl/bi_custom_ddl.sql",
    order: 3,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "starrocks_conn" },
      query: { file: "bi_custom_ddl.sql", timezone: "UTC" },
    },
  },
  {
    id: "crm-acctref-3",
    name: "extract_crm_accounts",
    dagName: "dag_CRM_integration_dbo_AccountReference",
    stage: "extract",
    taskType: "snapshot",
    sqlFilePath: "dags/CRM_integration/AccountReference/extract/data_model_task.sql",
    order: 4,
    taskConfig: {
      expectedWorkload: "medium",
      connection: { source: "sqlserver_Accounts", target: "starrocks_conn" },
      query: { file: "extract_crm_accounts.sql", timezone: "US/Eastern" },
    },
  },
  {
    id: "crm-acctref-4",
    name: "transform_account_to_datamodel",
    dagName: "dag_CRM_integration_dbo_AccountReference",
    stage: "transform",
    taskType: "snapshot",
    sqlFilePath: "dags/CRM_integration/AccountReference/transform/data_model_task.sql",
    order: 5,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "starrocks_conn" },
      query: { file: "data_model_task.sql", timezone: "US/Eastern" },
    },
  },
  {
    id: "crm-acctref-5",
    name: "cleanup_old_account_snapshots",
    dagName: "dag_CRM_integration_dbo_AccountReference",
    stage: "transform",
    taskType: "snapshot",
    sqlFilePath: "dags/CRM_integration/AccountReference/transform/cleanup_logs.sql",
    order: 6,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "starrocks_conn" },
      query: { file: "cleanup_logs.sql", timezone: "US/Eastern" },
    },
  },
  {
    id: "crm-acctref-6",
    name: "load_accounts_to_datamodel",
    dagName: "dag_CRM_integration_dbo_AccountReference",
    stage: "load",
    taskType: "snapshot",
    sqlFilePath: "dags/CRM_integration/AccountReference/load/load_to_datamodel.sql",
    order: 7,
    taskConfig: {
      expectedWorkload: "medium",
      connection: { source: "starrocks_conn", target: "starrocks_conn" },
      query: { file: "load_to_datamodel.sql", timezone: "US/Eastern" },
      loadTarget: { type: "DB", connection: { target: "starrocks_conn" } },
    },
  },
  {
    id: "crm-acctref-7",
    name: "dqa_rule_check_accounts",
    dagName: "dag_CRM_integration_dbo_AccountReference",
    stage: "dqa",
    taskType: "snapshot",
    sqlFilePath: "dags/CRM_integration/AccountReference/dqa/rule_check_accounts.sql",
    order: 8,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "starrocks_conn" },
      query: { file: "rule_check_accounts.sql", timezone: "US/Eastern" },
      dqa: { queryType: "single_query_notification", alertKind: "warning", tolerance: 0 },
    },
  },
  {
    id: "crm-acctref-8",
    name: "dqa_compare_counts_accounts",
    dagName: "dag_CRM_integration_dbo_AccountReference",
    stage: "dqa",
    taskType: "snapshot",
    sqlFilePath: "dags/CRM_integration/AccountReference/dqa/compare_counts.sql",
    order: 9,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "starrocks_conn", target: "starrocks_conn" },
      query: { file: "compare_counts.sql", timezone: "US/Eastern" },
      dqa: {
        queryType: "source_vs_target_query_comparison",
        alertKind: "error",
        tolerance: 0.01,
        sourceQueryFile: "source_count_by_day.sql",
        targetQueryFile: "target_count_by_day.sql",
        comparisonMetric: "count_per_day",
        groupBy: ["day"],
      },
    },
  },

  // ── dag_CRM_integration_gc_Game (snapshot) ──
  {
    id: "crm-game-1",
    name: "ddl_stage_Game",
    dagName: "dag_CRM_integration_gc_Game",
    stage: "ddl",
    taskType: "snapshot",
    sqlFilePath: "dags/CRM_integration/Game/ddl/create_table_stage.sql",
    order: 1,
  },
  {
    id: "crm-game-2",
    name: "ddl_datamodel_Game",
    dagName: "dag_CRM_integration_gc_Game",
    stage: "ddl",
    taskType: "snapshot",
    sqlFilePath: "dags/CRM_integration/Game/ddl/create_table_data_model.sql",
    order: 2,
  },
  {
    id: "crm-game-3",
    name: "extract_game_catalog",
    dagName: "dag_CRM_integration_gc_Game",
    stage: "extract",
    taskType: "snapshot",
    sqlFilePath: "dags/CRM_integration/Game/extract/data_model_task.sql",
    order: 3,
    taskConfig: {
      expectedWorkload: "high",
      connection: { source: "sqlserver_Gaming", target: "starrocks_conn" },
      query: { file: "extract_game_catalog.sql", timezone: "US/Eastern" },
    },
  },
  {
    id: "crm-game-4",
    name: "transform_game_to_datamodel",
    dagName: "dag_CRM_integration_gc_Game",
    stage: "transform",
    taskType: "snapshot",
    sqlFilePath: "dags/CRM_integration/Game/transform/data_model_task.sql",
    order: 4,
    taskConfig: {
      expectedWorkload: "medium",
      connection: { source: "starrocks_conn" },
      query: { file: "data_model_task.sql", timezone: "US/Eastern" },
    },
  },
  {
    id: "crm-game-5",
    name: "cleanup_old_game_snapshots",
    dagName: "dag_CRM_integration_gc_Game",
    stage: "transform",
    taskType: "snapshot",
    sqlFilePath: "dags/CRM_integration/Game/transform/cleanup_logs.sql",
    order: 5,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "starrocks_conn" },
      query: { file: "cleanup_logs.sql", timezone: "US/Eastern" },
    },
  },
  {
    id: "crm-game-6",
    name: "dqa_rule_check_game",
    dagName: "dag_CRM_integration_gc_Game",
    stage: "dqa",
    taskType: "snapshot",
    sqlFilePath: "dags/CRM_integration/Game/dqa/rule_check_game.sql",
    order: 6,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "starrocks_conn" },
      query: { file: "rule_check_game.sql", timezone: "US/Eastern" },
      dqa: { queryType: "single_query_notification", alertKind: "warning", tolerance: 0 },
    },
  },

  // ── dag_CRM_integration_tr_GameTransaction (incremental) ──
  {
    id: "crm-gametx-1",
    name: "create_table_stage",
    dagName: "dag_CRM_integration_tr_GameTransaction",
    stage: "ddl",
    taskType: "incremental",
    sqlFilePath: "dags/CRM_integration/GameTransaction/ddl/create_table_stage.sql",
    order: 1,
  },
  {
    id: "crm-gametx-2",
    name: "create_table_data_model",
    dagName: "dag_CRM_integration_tr_GameTransaction",
    stage: "ddl",
    taskType: "incremental",
    sqlFilePath: "dags/CRM_integration/GameTransaction/ddl/create_table_data_model.sql",
    order: 2,
  },
  {
    id: "crm-gametx-3",
    name: "extract_and_load",
    dagName: "dag_CRM_integration_tr_GameTransaction",
    stage: "extract",
    taskType: "incremental",
    sqlFilePath: "dags/CRM_integration/GameTransaction/extract/data_model_task.sql",
    order: 3,
    taskConfig: {
      expectedWorkload: "high",
      connection: { source: "sqlserver_Gaming", target: "starrocks_conn" },
      query: { file: "extract_game_transactions.sql", timezone: "US/Eastern" },
      loadTarget: { type: "DB", connection: { target: "starrocks_conn" } },
    },
  },
  {
    id: "crm-gametx-4",
    name: "data_model_task",
    dagName: "dag_CRM_integration_tr_GameTransaction",
    stage: "transform",
    taskType: "incremental",
    sqlFilePath: "dags/CRM_integration/GameTransaction/transform/data_model_task.sql",
    order: 4,
    taskConfig: {
      expectedWorkload: "medium",
      connection: { source: "starrocks_conn" },
      query: { file: "data_model_task.sql", timezone: "US/Eastern" },
    },
  },
  {
    id: "crm-gametx-5",
    name: "cleanup_stage_logs",
    dagName: "dag_CRM_integration_tr_GameTransaction",
    stage: "transform",
    taskType: "incremental",
    sqlFilePath: "dags/CRM_integration/GameTransaction/transform/cleanup_logs.sql",
    order: 5,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "starrocks_conn", target: "starrocks_conn" },
      query: { file: "cleanup_logs.sql", timezone: "US/Eastern" },
    },
  },
  {
    id: "crm-gametx-6",
    name: "dqa_compare_counts_gametx",
    dagName: "dag_CRM_integration_tr_GameTransaction",
    stage: "dqa",
    taskType: "incremental",
    sqlFilePath: "dags/CRM_integration/GameTransaction/dqa/compare_counts.sql",
    order: 6,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "sqlserver_Gaming", target: "starrocks_conn" },
      query: { file: "compare_counts.sql", timezone: "US/Eastern" },
      dqa: {
        queryType: "source_vs_target_query_comparison",
        alertKind: "error",
        tolerance: 0.01,
        sourceQueryFile: "source_count_by_day.sql",
        targetQueryFile: "target_count_by_day.sql",
        comparisonMetric: "count_per_day",
        groupBy: ["day"],
      },
    },
  },

  // ── dag_BEATS_integration_dbo_AccountLogType (snapshot) ──
  {
    id: "beats-acctlog-1",
    name: "create_table_stage",
    dagName: "dag_BEATS_integration_dbo_AccountLogType",
    stage: "extract",
    taskType: "snapshot",
    sqlFilePath: "dags/BEATS_integration/AccountLogType/extract/data_model_task.sql",
    order: 1,
  },
  {
    id: "beats-acctlog-2",
    name: "create_table_data_model",
    dagName: "dag_BEATS_integration_dbo_AccountLogType",
    stage: "ddl",
    taskType: "snapshot",
    sqlFilePath: "dags/BEATS_integration/AccountLogType/ddl/create_table_data_model.sql",
    order: 2,
  },
  {
    id: "beats-acctlog-3",
    name: "extract_and_load",
    dagName: "dag_BEATS_integration_dbo_AccountLogType",
    stage: "ddl",
    taskType: "snapshot",
    sqlFilePath: "dags/BEATS_integration/AccountLogType/ddl/create_table_stage.sql",
    order: 3,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "sqlserver_Accounts", target: "starrocks_conn" },
      query: { file: "extract_account_log_type.sql", timezone: "UTC" },
    },
  },
  {
    id: "beats-acctlog-4",
    name: "data_model_task",
    dagName: "dag_BEATS_integration_dbo_AccountLogType",
    stage: "transform",
    taskType: "snapshot",
    sqlFilePath: "dags/BEATS_integration/AccountLogType/transform/data_model_task.sql",
    order: 4,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "starrocks_conn" },
      query: { file: "data_model_task.sql", timezone: "US/Eastern" },
    },
  },
  {
    id: "beats-acctlog-5",
    name: "delete_logs",
    dagName: "dag_BEATS_integration_dbo_AccountLogType",
    stage: "transform",
    taskType: "snapshot",
    sqlFilePath: "dags/BEATS_integration/AccountLogType/transform/cleanup_logs.sql",
    order: 5,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "starrocks_conn" },
      query: { file: "cleanup_logs.sql", timezone: "US/Eastern" },
    },
  },
  {
    id: "beats-acctlog-6",
    name: "dqa_rule_check_acctlog",
    dagName: "dag_BEATS_integration_dbo_AccountLogType",
    stage: "dqa",
    taskType: "snapshot",
    sqlFilePath: "dags/BEATS_integration/AccountLogType/dqa/rule_check_acctlog.sql",
    order: 6,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "starrocks_conn" },
      query: { file: "rule_check_acctlog.sql", timezone: "US/Eastern" },
      dqa: { queryType: "single_query_notification", alertKind: "warning", tolerance: 0 },
    },
  },

  // ── dag_data_sources_tr_DailyTransactionAmount (incremental) ──
  {
    id: "ds-dailytx-1",
    name: "create_table_stage",
    dagName: "dag_data_sources_tr_DailyTransactionAmount",
    stage: "ddl",
    taskType: "incremental",
    sqlFilePath: "dags/data_sources/gaming_integration/sqlserver_gamingintegration_tr_dailytransactionamount/ddl/create_table_stage.sql",
    order: 1,
  },
  {
    id: "ds-dailytx-2",
    name: "create_table_data_model",
    dagName: "dag_data_sources_tr_DailyTransactionAmount",
    stage: "ddl",
    taskType: "incremental",
    sqlFilePath: "dags/data_sources/gaming_integration/sqlserver_gamingintegration_tr_dailytransactionamount/ddl/create_table_data_model.sql",
    order: 2,
  },
  {
    id: "ds-dailytx-3",
    name: "extract_and_load",
    dagName: "dag_data_sources_tr_DailyTransactionAmount",
    stage: "extract",
    taskType: "incremental",
    sqlFilePath: "dags/data_sources/gaming_integration/sqlserver_gamingintegration_tr_dailytransactionamount/extract/select_from_source.sql",
    order: 3,
    taskConfig: {
      expectedWorkload: "high",
      connection: { source: "sqlserver_Gaming", target: "starrocks_conn" },
      query: { file: "select_from_source.sql", timezone: "US/Eastern" },
      loadTarget: {
        type: "Email",
        connection: { target: "starrocks_conn" },
        to: ["reports@company.com"],
        cc: ["data-team@company.com"],
        subject: "Daily Transaction Amount Report",
        body: "Attached is the daily transaction amount report.",
      },
    },
  },
  {
    id: "ds-dailytx-4",
    name: "data_model_task",
    dagName: "dag_data_sources_tr_DailyTransactionAmount",
    stage: "transform",
    taskType: "incremental",
    sqlFilePath: "dags/data_sources/gaming_integration/sqlserver_gamingintegration_tr_dailytransactionamount/transform/stage_to_data_model.sql",
    order: 4,
    taskConfig: {
      expectedWorkload: "medium",
      connection: { source: "starrocks_conn" },
      query: { file: "stage_to_data_model.sql", timezone: "US/Eastern" },
    },
  },
  {
    id: "ds-dailytx-5",
    name: "cleanup_stage_old_records",
    dagName: "dag_data_sources_tr_DailyTransactionAmount",
    stage: "transform",
    taskType: "incremental",
    sqlFilePath: "dags/data_sources/gaming_integration/sqlserver_gamingintegration_tr_dailytransactionamount/transform/cleanup_stage_old_records.sql",
    order: 5,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "starrocks_conn" },
      query: { file: "cleanup_stage_old_records.sql", timezone: "US/Eastern" },
    },
  },
  {
    id: "ds-dailytx-6",
    name: "dqa_rule_check_dailytx",
    dagName: "dag_data_sources_tr_DailyTransactionAmount",
    stage: "dqa",
    taskType: "incremental",
    sqlFilePath: "dags/data_sources/gaming_integration/sqlserver_gamingintegration_tr_dailytransactionamount/dqa/rule_check_dailytx.sql",
    order: 6,
    taskConfig: {
      expectedWorkload: "low",
      connection: { source: "starrocks_conn" },
      query: { file: "rule_check_dailytx.sql", timezone: "US/Eastern" },
      dqa: { queryType: "single_query_notification", alertKind: "error", tolerance: 0.01 },
    },
  },
];

export const initialPipelineTasks: PipelineTask[] = deepAnonymize(RAW_INITIAL_PIPELINE_TASKS);

export function getTasksForPipeline(tasks: PipelineTask[], dagName: string): PipelineTask[] {
  return tasks
    .filter((t) => t.dagName === dagName)
    .sort((a, b) => a.order - b.order);
}

export function getNonDdlTasksForPipeline(tasks: PipelineTask[], dagName: string): PipelineTask[] {
  return tasks
    .filter((t) => t.dagName === dagName && !isTransparentSystemDdlTask(t.name, t.sqlFilePath))
    .sort((a, b) => a.order - b.order);
}
