import { PipelineTask } from "./types";

// 5 tasks per DAG × 5 DAGs = 25 tasks
// Pattern per DAG: create_table_stage → create_table_data_model → extract_and_load → data_model_task → delete_logs

export const initialPipelineTasks: PipelineTask[] = [
  // ── dag_CRM_integration_dbo_AccountReference (snapshot) ──
  {
    id: "crm-acctref-1",
    name: "ddl_stage_AccountReference",
    dagName: "dag_CRM_integration_dbo_AccountReference",
    stage: "extract",
    taskType: "snapshot",
    sqlFilePath: "sql/AccountReference/ddl_stage_account_reference.sql",
    order: 1,
  },
  {
    id: "crm-acctref-2",
    name: "ddl_datamodel_AccountReference",
    dagName: "dag_CRM_integration_dbo_AccountReference",
    stage: "extract",
    taskType: "snapshot",
    sqlFilePath: "sql/AccountReference/ddl_datamodel_account_reference.sql",
    order: 2,
  },
  {
    id: "crm-acctref-3",
    name: "extract_crm_accounts",
    dagName: "dag_CRM_integration_dbo_AccountReference",
    stage: "load",
    taskType: "snapshot",
    sqlFilePath: "sql/AccountReference/extract_crm_accounts.sql",
    order: 3,
  },
  {
    id: "crm-acctref-4",
    name: "transform_account_to_datamodel",
    dagName: "dag_CRM_integration_dbo_AccountReference",
    stage: "transform",
    taskType: "snapshot",
    sqlFilePath: "sql/AccountReference/transform_account_to_datamodel.sql",
    order: 4,
  },
  {
    id: "crm-acctref-5",
    name: "cleanup_old_account_snapshots",
    dagName: "dag_CRM_integration_dbo_AccountReference",
    stage: "dqa",
    taskType: "snapshot",
    sqlFilePath: "sql/AccountReference/cleanup_old_account_snapshots.sql",
    order: 5,
  },

  // ── dag_CRM_integration_gc_Game (snapshot) ──
  {
    id: "crm-game-1",
    name: "ddl_stage_Game",
    dagName: "dag_CRM_integration_gc_Game",
    stage: "extract",
    taskType: "snapshot",
    sqlFilePath: "sql/Game/ddl_stage_game.sql",
    order: 1,
  },
  {
    id: "crm-game-2",
    name: "ddl_datamodel_Game",
    dagName: "dag_CRM_integration_gc_Game",
    stage: "extract",
    taskType: "snapshot",
    sqlFilePath: "sql/Game/ddl_datamodel_game.sql",
    order: 2,
  },
  {
    id: "crm-game-3",
    name: "extract_game_catalog",
    dagName: "dag_CRM_integration_gc_Game",
    stage: "load",
    taskType: "snapshot",
    sqlFilePath: "sql/Game/extract_game_catalog.sql",
    order: 3,
  },
  {
    id: "crm-game-4",
    name: "transform_game_to_datamodel",
    dagName: "dag_CRM_integration_gc_Game",
    stage: "transform",
    taskType: "snapshot",
    sqlFilePath: "sql/Game/transform_game_to_datamodel.sql",
    order: 4,
  },
  {
    id: "crm-game-5",
    name: "cleanup_old_game_snapshots",
    dagName: "dag_CRM_integration_gc_Game",
    stage: "dqa",
    taskType: "snapshot",
    sqlFilePath: "sql/Game/cleanup_old_game_snapshots.sql",
    order: 5,
  },

  // ── dag_CRM_integration_tr_GameTransaction (incremental) ──
  {
    id: "crm-gametx-1",
    name: "create_table_stage",
    dagName: "dag_CRM_integration_tr_GameTransaction",
    stage: "extract",
    taskType: "incremental",
    sqlFilePath: "dags/CRM_integration/GameTransaction/sql_files/ddl/create_table_stage.sql",
    order: 1,
  },
  {
    id: "crm-gametx-2",
    name: "create_table_data_model",
    dagName: "dag_CRM_integration_tr_GameTransaction",
    stage: "extract",
    taskType: "incremental",
    sqlFilePath: "dags/CRM_integration/GameTransaction/sql_files/ddl/create_table_data_model.sql",
    order: 2,
  },
  {
    id: "crm-gametx-3",
    name: "extract_and_load",
    dagName: "dag_CRM_integration_tr_GameTransaction",
    stage: "load",
    taskType: "incremental",
    sqlFilePath: "dags/CRM_integration/GameTransaction/sql_files/ddl/create_table_stage.sql",
    order: 3,
  },
  {
    id: "crm-gametx-4",
    name: "data_model_task",
    dagName: "dag_CRM_integration_tr_GameTransaction",
    stage: "transform",
    taskType: "incremental",
    sqlFilePath: "dags/CRM_integration/GameTransaction/sql_files/transformations/data_model_task.sql",
    order: 4,
  },
  {
    id: "crm-gametx-5",
    name: "delete_logs",
    dagName: "dag_CRM_integration_tr_GameTransaction",
    stage: "dqa",
    taskType: "incremental",
    sqlFilePath: "dags/CRM_integration/GameTransaction/sql_files/ddl/create_table_data_model.sql",
    order: 5,
  },

  // ── dag_BEATS_integration_dbo_AccountLogType (snapshot) ──
  {
    id: "beats-acctlog-1",
    name: "create_table_stage",
    dagName: "dag_BEATS_integration_dbo_AccountLogType",
    stage: "extract",
    taskType: "snapshot",
    sqlFilePath: "dags/BEATS_integration/AccountLogType/sql_files/ddl/create_table_stage.sql",
    order: 1,
  },
  {
    id: "beats-acctlog-2",
    name: "create_table_data_model",
    dagName: "dag_BEATS_integration_dbo_AccountLogType",
    stage: "extract",
    taskType: "snapshot",
    sqlFilePath: "dags/BEATS_integration/AccountLogType/sql_files/ddl/create_table_data_model.sql",
    order: 2,
  },
  {
    id: "beats-acctlog-3",
    name: "extract_and_load",
    dagName: "dag_BEATS_integration_dbo_AccountLogType",
    stage: "load",
    taskType: "snapshot",
    sqlFilePath: "dags/BEATS_integration/AccountLogType/sql_files/ddl/create_table_stage.sql",
    order: 3,
  },
  {
    id: "beats-acctlog-4",
    name: "data_model_task",
    dagName: "dag_BEATS_integration_dbo_AccountLogType",
    stage: "transform",
    taskType: "snapshot",
    sqlFilePath: "dags/BEATS_integration/AccountLogType/sql_files/transformations/data_model_task.sql",
    order: 4,
  },
  {
    id: "beats-acctlog-5",
    name: "delete_logs",
    dagName: "dag_BEATS_integration_dbo_AccountLogType",
    stage: "dqa",
    taskType: "snapshot",
    sqlFilePath: "dags/BEATS_integration/AccountLogType/sql_files/transformations/delete_logs.sql",
    order: 5,
  },

  // ── dag_data_sources_tr_DailyTransactionAmount (incremental) ──
  {
    id: "ds-dailytx-1",
    name: "create_table_stage",
    dagName: "dag_data_sources_tr_DailyTransactionAmount",
    stage: "extract",
    taskType: "incremental",
    sqlFilePath: "dags/data_sources/gaming_integration/sqlserver_gamingintegration_tr_dailytransactionamount/sql_files/ddl/create_table_stage.sql",
    order: 1,
  },
  {
    id: "ds-dailytx-2",
    name: "create_table_data_model",
    dagName: "dag_data_sources_tr_DailyTransactionAmount",
    stage: "extract",
    taskType: "incremental",
    sqlFilePath: "dags/data_sources/gaming_integration/sqlserver_gamingintegration_tr_dailytransactionamount/sql_files/ddl/create_table_data_model.sql",
    order: 2,
  },
  {
    id: "ds-dailytx-3",
    name: "extract_and_load",
    dagName: "dag_data_sources_tr_DailyTransactionAmount",
    stage: "load",
    taskType: "incremental",
    sqlFilePath: "dags/data_sources/gaming_integration/sqlserver_gamingintegration_tr_dailytransactionamount/sql_files/dml/select_from_source.sql",
    order: 3,
  },
  {
    id: "ds-dailytx-4",
    name: "data_model_task",
    dagName: "dag_data_sources_tr_DailyTransactionAmount",
    stage: "transform",
    taskType: "incremental",
    sqlFilePath: "dags/data_sources/gaming_integration/sqlserver_gamingintegration_tr_dailytransactionamount/sql_files/dml/stage_to_data_model.sql",
    order: 4,
  },
  {
    id: "ds-dailytx-5",
    name: "delete_logs",
    dagName: "dag_data_sources_tr_DailyTransactionAmount",
    stage: "dqa",
    taskType: "incremental",
    sqlFilePath: "dags/data_sources/gaming_integration/sqlserver_gamingintegration_tr_dailytransactionamount/sql_files/dml/delete_stage_old_records.sql",
    order: 5,
  },
];

export function getTasksForPipeline(tasks: PipelineTask[], dagName: string): PipelineTask[] {
  return tasks
    .filter((t) => t.dagName === dagName)
    .sort((a, b) => a.order - b.order);
}
